services:
  booking-gateway-service:
    image: booking-gateway-service:1.0
    container_name: booking-gateway-service
    build:
      context: ./booking-gateway-service
      dockerfile: Dockerfile
    env_file: 
      - ./.env
    ports:
      - "8080:8080"
  booking-auth-service:
    image: booking-auth-service:1.0
    container_name: booking-auth-service
    build:
      context: ./booking-auth-service
      dockerfile: Dockerfile
    env_file: 
      - ./.env
    ports:
      - "8081:8081"
    networks:
      - booking-network
    depends_on:
      auth-service-db:
        condition: service_healthy
  booking-account-service:
    image: booking-account-service:1.0
    container_name: booking-account-service
    build:
      context: ./booking-account-service
      dockerfile: Dockerfile
    env_file: 
      - ./.env
    ports:
      - "8082:8082"
    networks:
      - booking-network
    depends_on:
      account-service-db:
        condition: service_healthy
  booking-accommodation-service:
    image: booking-accommodation-service:1.0
    container_name: booking-accommodation-service
    build:
      context: ./booking-accommodation-service
      dockerfile: Dockerfile
    env_file: 
      - ./.env
    ports:
      - "8083:8083"
  booking-reservation-service:
    image: booking-reservation-service:1.0
    container_name: booking-reservation-service
    build:
      context: ./booking-reservation-service
      dockerfile: Dockerfile
    env_file: 
      - ./.env
    ports:
      - "8084:8084"

  auth-service-db:
    image: postgres:18.3-bookworm
    container_name: auth-service-db
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${DEFAULT_DB_USER}
      POSTGRES_PASSWORD: ${DEFAULT_DB_PASSWORD}
    volumes:
      - auth-db-data:/var/lib/postgresql
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DEFAULT_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - booking-network
  account-service-db:
    image: postgres:18.3-bookworm
    container_name: account-service-db
    environment:
      POSTGRES_DB: ${ACCOUNT_DB_NAME}
      POSTGRES_USER: ${DEFAULT_DB_USER}
      POSTGRES_PASSWORD: ${DEFAULT_DB_PASSWORD}
    volumes:
      - account-db-data:/var/lib/postgresql
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DEFAULT_DB_USER} -d ${ACCOUNT_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - booking-network
      
networks:
  booking-network:
    driver: bridge

volumes:
  auth-db-data:
  account-db-data: