spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/auth/**
              filters:
               - StripPrefix=1

            - id: account-service
              uri: ${ACCOUNT_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/account/**
              filters:
                - StripPrefix=1

            - id: accommodation-service
              uri: ${ACCOMMODATION_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/accommodation/**
              filters:
                - StripPrefix=1

            - id: reservation-service
              uri: ${RESERVATION_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/reservation/**
              filters:
                - StripPrefix=1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
    health:
      show-details: always
