spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/signin, /signup
              filters:
               - RewritePath=/signin, /auth/signin
               - RewritePath=/signup, /auth/signup

            - id: account-service
              uri: ${ACCOUNT_SERVICE_URL}
              predicates:
                - Path=/account, /account/delete
server:
  port: 8080